//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorWYDDB23.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class resource_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resource_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorWYDDB23.Shared.Resources.resource.en", typeof(resource_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string A_Carregar___ {
            get {
                return ResourceManager.GetString("A Carregar...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page you’re looking for doesn’t exist.
        /// </summary>
        public static string A_página_que_está_a_tentar_aceder_não_existe {
            get {
                return ResourceManager.GetString("A página que está a tentar aceder não existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized access only to staff.
        /// </summary>
        public static string Acesso_autorizado_apenas_a_staff {
            get {
                return ResourceManager.GetString("Acesso autorizado apenas a staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda.
        /// </summary>
        public static string Agenda {
            get {
                return ResourceManager.GetString("Agenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYM Day.
        /// </summary>
        public static string Dia_MJS {
            get {
                return ResourceManager.GetString("Dia MJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Himn.
        /// </summary>
        public static string Hino {
            get {
                return ResourceManager.GetString("Hino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Início {
            get {
                return ResourceManager.GetString("Início", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Mapa {
            get {
                return ResourceManager.GetString("Mapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Authorized.
        /// </summary>
        public static string Não_Autorizado {
            get {
                return ResourceManager.GetString("Não Autorizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,.
        /// </summary>
        public static string Olá_ {
            get {
                return ResourceManager.GetString("Olá,", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Outros {
            get {
                return ResourceManager.GetString("Outros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page not found.
        /// </summary>
        public static string Página_não_encontrada {
            get {
                return ResourceManager.GetString("Página não encontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHORUS:.
        /// </summary>
        public static string REFRÃO_ {
            get {
                return ResourceManager.GetString("REFRÃO:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Home.
        /// </summary>
        public static string Voltar_ao_Início {
            get {
                return ResourceManager.GetString("Voltar ao Início", resourceCulture);
            }
        }
    }
}
