//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorWYDDB23.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorWYDDB23.Shared.Resources.resource", typeof(resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Carregar....
        /// </summary>
        public static string A_Carregar___ {
            get {
                return ResourceManager.GetString("A Carregar...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A página que está a tentar aceder não existe.
        /// </summary>
        public static string A_página_que_está_a_tentar_aceder_não_existe {
            get {
                return ResourceManager.GetString("A página que está a tentar aceder não existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso autorizado apenas a staff.
        /// </summary>
        public static string Acesso_autorizado_apenas_a_staff {
            get {
                return ResourceManager.GetString("Acesso autorizado apenas a staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda.
        /// </summary>
        public static string Agenda {
            get {
                return ResourceManager.GetString("Agenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dia MJS.
        /// </summary>
        public static string Dia_MJS {
            get {
                return ResourceManager.GetString("Dia MJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hino.
        /// </summary>
        public static string Hino {
            get {
                return ResourceManager.GetString("Hino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início.
        /// </summary>
        public static string Início {
            get {
                return ResourceManager.GetString("Início", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapa.
        /// </summary>
        public static string Mapa {
            get {
                return ResourceManager.GetString("Mapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não Autorizado.
        /// </summary>
        public static string Não_Autorizado {
            get {
                return ResourceManager.GetString("Não Autorizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olá,.
        /// </summary>
        public static string Olá_ {
            get {
                return ResourceManager.GetString("Olá,", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outros.
        /// </summary>
        public static string Outros {
            get {
                return ResourceManager.GetString("Outros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página não encontrada.
        /// </summary>
        public static string Página_não_encontrada {
            get {
                return ResourceManager.GetString("Página não encontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFRÃO:.
        /// </summary>
        public static string REFRÃO_ {
            get {
                return ResourceManager.GetString("REFRÃO:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar ao Início.
        /// </summary>
        public static string Voltar_ao_Início {
            get {
                return ResourceManager.GetString("Voltar ao Início", resourceCulture);
            }
        }
    }
}
